enum VisitStrings {
    static let table: [AppLanguage: [String: String]] = [
        .en: en,
        .de: de,
    ]

    static let en: [String: String] = [
        "more.visit": "Doctor visit",
        "more.visitTitle": "Visit summary",
        "more.visitBody": "PDF of recent cycles for an appointment. Stays on this device until you share it.",
        "more.visitLabel": "View PDF",
        "more.visitFailed": "Couldn’t create the PDF.",
        "visit.title": "PeriMedi visit summary",
        "visit.generated": "Generated {{date}}",
        "visit.range.two": "{{start}} – {{end}} (last 2 completed cycles)",
        "visit.range.one": "{{start}} – {{end}} (last completed cycle)",
        "visit.range.fourWeeks": "{{start}} – {{end}} (last 4 weeks)",
        "visit.range.twelveWeeks": "{{start}} – {{end}} (last 12 weeks)",
        "visit.effect": "Effect",
        "visit.meds": "Medications",
        "visit.medLine": "{{name}} · {{dose}} · {{taken}} of {{planned}} taken ({{percent}}%)",
        "visit.noMeds": "No planned doses in this range.",
        "visit.changes": "Dose and schedule changes",
        "visit.change.dose": "{{date}}: {{name}} dose {{previous}} → {{new}}. Context only, not a cause.",
        "visit.change.schedule": "{{date}}: {{name}} schedule {{previous}} → {{new}}. Context only, not a cause.",
        "visit.noChanges": "None in this range.",
        "visit.periods": "Periods",
        "visit.periodRow": "{{start}} – {{end}}",
        "visit.noPeriods": "None in this range.",
        "visit.symptoms": "Symptoms",
        "visit.symptomHeader": "Symptom · days scored · average",
        "visit.symptomRow": "{{name}} · {{days}} days · average {{mean}}",
        "visit.noSymptoms": "No scored symptoms in this range.",
        "visit.disclaimer": "This PDF is not a medical record and not medical advice. It is a personal summary from PeriMedi.",
        "visit.share": "Share",
        "visit.range.sheet": "Which cycles?",
        "visit.range.hint": "Pick a completed cycle. You can include the cycle before it.",
        "visit.range.previous": "Include previous cycle",
        "visit.range.continue": "Continue",
        "visit.range.completed": "Completed cycle",
        "visit.range.empty": "No completed cycle yet. The PDF uses the last 4 or 12 weeks.",
    ]

    static let de: [String: String] = [
        "more.visit": "Arztbesuch",
        "more.visitTitle": "Besuchszusammenfassung",
        "more.visitBody": "PDF der letzten Zyklen für den Termin. Bleibt auf dem Gerät, bis du es teilst.",
        "more.visitLabel": "PDF anzeigen",
        "more.visitFailed": "PDF konnte nicht erstellt werden.",
        "visit.title": "PeriMedi — Besuchszusammenfassung",
        "visit.generated": "Erstellt am {{date}}",
        "visit.range.two": "{{start}} – {{end}} (letzte 2 abgeschlossene Zyklen)",
        "visit.range.one": "{{start}} – {{end}} (letzter abgeschlossener Zyklus)",
        "visit.range.fourWeeks": "{{start}} – {{end}} (letzte 4 Wochen)",
        "visit.range.twelveWeeks": "{{start}} – {{end}} (letzte 12 Wochen)",
        "visit.effect": "Effekt",
        "visit.meds": "Medikamente",
        "visit.medLine": "{{name}} · {{dose}} · {{taken}} von {{planned}} eingenommen ({{percent}} %)",
        "visit.noMeds": "Keine geplanten Dosen in diesem Zeitraum.",
        "visit.changes": "Dosis- und Schemawechsel",
        "visit.change.dose": "{{date}}: {{name}} Dosis {{previous}} → {{new}}. Nur Kontext, keine Ursache.",
        "visit.change.schedule": "{{date}}: {{name}} Schema {{previous}} → {{new}}. Nur Kontext, keine Ursache.",
        "visit.noChanges": "Keine in diesem Zeitraum.",
        "visit.periods": "Perioden",
        "visit.periodRow": "{{start}} – {{end}}",
        "visit.noPeriods": "Keine in diesem Zeitraum.",
        "visit.symptoms": "Symptome",
        "visit.symptomHeader": "Symptom · erfasste Tage · Mittel",
        "visit.symptomRow": "{{name}} · {{days}} Tage · Mittel {{mean}}",
        "visit.noSymptoms": "Keine erfassten Symptome in diesem Zeitraum.",
        "visit.disclaimer": "Dieses PDF ist keine Patientenakte und kein medizinischer Rat. Es ist eine persönliche Zusammenfassung aus PeriMedi.",
        "visit.share": "Teilen",
        "visit.range.sheet": "Welche Zyklen?",
        "visit.range.hint": "Wähle einen abgeschlossenen Zyklus. Du kannst den davor einbeziehen.",
        "visit.range.previous": "Vorherigen Zyklus einbeziehen",
        "visit.range.continue": "Weiter",
        "visit.range.completed": "Abgeschlossener Zyklus",
        "visit.range.empty": "Noch kein abgeschlossener Zyklus. Das PDF nutzt die letzten 4 oder 12 Wochen.",
    ]
}
